import time

name = input('Please Enter Your Name \n')
 
print('starting bot...')
time.sleep(4)
print('load 4%')
time.sleep(1)
print('load 13%')
time.sleep(1)
print('load 34%')
time.sleep(1)
print('load 48%')
time.sleep(.7)
print('load 56%')
time.sleep(.7)
print('load 69% (nice)')
time.sleep(1)
print('load 84%')
time.sleep(.6)
print('load 95%')
time.sleep(2)
print('load 100%')
time.sleep(3)
print('started!')

print('Hi', name, ', How are you, I am a bot named Aiden!')
